config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
  validates :buy_date, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    def feed_books
    Book.where(user_id: [self.id])
    end
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
   
   has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  def counts(user)
    @count_books = user.books.count
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  def index
      @books = current_user.books.order(id: :desc).page(params[:page])
  end

  def show
  end

  def new
      @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:success] = '積読が正常に追加されました'
      redirect_to root_url
    else
      @books = current_user.feed_books.order(id: :desc).page(params[:page])
      flash.now[:danger] = '積読が追加されませんでした'
      render 'books/new'
    end
  end

  def edit
    
  end

  def update

    if @book.update(book_params)
      flash[:success] = '積読は正常に更新されました'
      redirect_to @book
    else
      flash.now[:danger] = '積読は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = '積読は正常に削除されました'
    redirect_to root_url
  end
  
  private
  
  
  # Strong Parameter
  def book_params
    params.require(:book).permit(:status,:title,:buy_date)
  end
  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    unless @book
      redirect_to root_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

   def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
   end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/books/_books.html.erb
<ul class="list-unstyled">
  <% @books.each do |book| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(book.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to book.user.name, user_path(book.user) %> <span class="text-muted">posted at <%= book.created_at %></span>
        </div>
        <div>
          <p><%= book.title %></p>
          <p><%= book.status %></p>
          <p><%= book.buy_date %></p>
        </div>
        <div>
          <% if current_user == book.user %>
            <%= link_to "削除", book, method: :destroy, data: { confirm: "消しても本当にいいですか?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate books %>
</ul>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% book.errors.full_messages.each do |bok| %>
          <li><%= bok %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status %>

  <%= f.label :title, 'タイトル' %>
  <%= f.text_field :title %>
  
  <%= f.label :buy_date, '購入日' %>
  <%= f.text_field :buy_date %>

  <%= f.submit '追加' %>
<% end %>

app/views/books/edit.html.erb
<h1>id: <%= @book.id %> の積読編集ページ</h1>

<%= render 'form', book: @book %>

<%= link_to '一覧に戻る', books_path %>

app/views/books/index.html.erb
<h1>積読一覧</h1>

<ul>
  <% @books.each do |book| %>
    <li>
      <%= link_to book.id,book %> : <%= book.status %> &gt; <%= book.title %>&gt; <%= book.buy_date %>
    </li>
  <% end %>
</ul>
<%= link_to '新規積読の投稿', new_book_path %>

app/views/books/new.html.erb
<h1>積読新規作成ページ</h1>

<%= render 'form', book: @book %>

<%= link_to '一覧に戻る', books_path %>

app/views/books/show.html.erb
<h1>id: <%= @book.id %> の積読詳細ページ</h1>

<p>ステータス: <%= @book.status %></p>
<p>タイトル：<%= @book.title %></p>
<p>購入日：<%= @book.buy_date %></p>

<%= link_to '一覧に戻る', books_path %>
<%= link_to 'この積読を編集する', edit_book_path(@book) %>
<%= link_to 'この積読を削除する', @book, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/layouts/_error_books.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_error_tasks.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_flash_books.html.erb
<% flash.each do |book_type, book| %>
  <div class="alert alert-<%= book_type %>"><%= book %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">積読管理</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>積読リスト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_books' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="text-center">
  <h1>会員登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_books', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      

      <%= f.submit '会員登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>